name: generate new demo

on:
  push:
    branches: [main]

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: dispatch generator
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: generator
          repo: claudiacachayosorio/demo-gifs
          token: ${{ secrets.PAT_DISPATCH_GIF }}
          inputs: '{ "repo": "${{ github.repository }}" }'