name: generator

on:
  workflow_dispatch:
    inputs:
      repo:
        description: "Project repository that dispatched this workflow."
        required: true

jobs:
  generator:
    runs-on: ubuntu-latest

    steps:
      - name: checkout project repo
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.inputs.repo }}

      - name: store inputs from package.json
        uses: myrotvorets/info-from-package-json-action@1.0.0
        id: pkg

      - name: checkout generator repo
        uses: actions/checkout@v2

      - name: set up node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: create gif
        run: |
          npm install
          npm run start browser ${{ steps.pkg.outputs.packageName }} ${{ steps.pkg.outputs.packageHomepage }}

      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: move gif to S3 bucket
        run: aws s3 mv ${{ steps.pkg.outputs.packageName }}.gif s3://cco-demo-gifs --acl public-read