name: terminal

on:
  push:
    branches: [main]

jobs:
  terminal:
    runs-on: ubuntu-latest

    steps:
      - name: install softwares
        run: |
          git clone --recursive https://github.com/asciinema/asciicast2gif.git
          sudo apt-add-repository ppa:zanchey/asciinema
          sudo apt-get update
          sudo apt-get install asciinema
          sudo apt-get install gifsicle

      - name: checkout repo
        uses: actions/checkout@v2
        with:
          path: asciicast2gif

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: start recording
        run: asciinema rec demo.cast
        working-directory: asciicast2gif

      - name: run demo
        run: |
          npm install
          npm run demo
        working-directory: asciicast2gif

      - name: stop recording
        run: exit
        working-directory: asciicast2gif
      - run: ls
