name: terminal

on:
  push:
    branches: [main]

jobs:
  terminal:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '14.12.0'

      - run: npm install -g terminalizer
      - run: terminalizer record test

      - run: |
          npm install
          npm run demo

      - run: terminalizer render test
      - run: ls
