name: terminal

on:
  push:
    branches: [main]

jobs:
  terminal:
    runs-on: ubuntu-latest

    steps:
      - name: install software
        run: |
          git clone https://github.com/asciinema/asciinema.git

      - name: checkout repo
        uses: actions/checkout@v2
        with:
          path: asciinema

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: start recording
        run: asciinema rec demo.cast
        working-directory: asciinema

      - name: run demo
        run: |
          npm install
          npm run demo
        working-directory: asciinema

      - name: stop recording
        run: exit
        working-directory: asciinema
  
      - run: ls
        working-directory: asciinema
