name: terminal

on:
  push:
    branches: [main]

jobs:
  terminal:
    runs-on: ubuntu-latest

    steps:
      - name: install softwares
        run: |
          sudo pip3 install asciinema

      - name: checkout repo
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: start recording
        run: asciinema rec demo.cast

      - name: run demo
        run: |
          npm install
          npm run demo

      - name: stop recording
        run: exit
      - run: ls
