name: terminal

on:
  push:
    branches: [main]

jobs:
  terminal:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '14.12.0'

      - run: sudo apt-get install xdotool

      - run: npm install -g terminalizer
      - run: terminalizer init
      - run: terminalizer record test
      - run: xdotool key ctrl+c

      #- run: |
          #npm install
          #npm run demo

      #- run: terminalizer render test
      #- run: ls
