name: terminal

on:
  push:
    branches: [main]

jobs:
  terminal:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      #- run: sudo apt-get install xdotool

      - run: npm install -g terminalizer
      - run: |
          cd terminalizer
          pwd
          ls
      #- run: terminalizer init
      #- run: terminalizer record test
      #- run: xdotool key ctrl+d

      #- run: |
          #npm install
          #npm run demo

      #- run: terminalizer render test
      #- run: ls
