name: terminal

on:
  push:
    branches: [main]

jobs:
  terminal:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: asciicast2gif

    steps:
      - run: |
          pwd
          ls

      - name: install asciicast2gif
        run: git clone --recursive https://github.com/asciinema/asciicast2gif.git

      - name: checkout repo
        uses: actions/checkout@v2
        #with:
          #path: asciicast2gif

      - run: |
          pwd
          ls
