name: terminal

on:
  push:
    branches: [main]

jobs:
  terminal:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          repository: claudiacachayosorio/terminalizer

      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: npm install

      #- run: sudo apt-get install xdotool
      - run: terminalizer init
      #- run: terminalizer record test
      #- run: xdotool key ctrl+d

      #- run: |
          #npm install
          #npm run demo

      #- run: terminalizer render test
      #- run: ls
