name: PR
run-name: >-
  PR #${{ github.event.pull_request.number }}
  from ${{ github.head_ref }} (${{ github.event.action }})

on:
  pull_request:
    branches: [main]
    types:
      - opened
      - reopened
      - edited

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  pull-requests: read

jobs:
  pr:
    runs-on: ubuntu-latest

    steps:
      - name: Validate title
        uses: amannn/action-semantic-pull-request@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
