name: terminal

on:
  push:
    branches: [main]

jobs:
  terminal:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - run: curl -sL http://www.lcdf.org/gifsicle/gifsicle-1.93.tar.gz | tar -zx
      - run: ls

      - run: |
          cd gifsicle-1.93
          autoscan

      - run: |
          cd gifsicle-1.93
          mv ./configure.scan ./configure.ac

      - run: |
          cd gifsicle-1.93
          autoreconf -i

      - run: |
          cd gifsicle-1.93
          ./configure

      - run: |
          cd gifsicle-1.93
          make install
