name: terminal

on:
  push:
    branches: [main]

jobs:
  terminal:
    runs-on: ubuntu-latest

    steps:
      - run: curl -sL http://www.lcdf.org/gifsicle/gifsicle-1.93.tar.gz | tar -zx
      - run: pwd

      - run: |
          cd gifsicle-1.93
          pwd
          autoscan

      - run: |
          cd gifsicle-1.93
          pwd
          mv ./configure.scan ./configure.ac

      - run: |
          cd gifsicle-1.93
          autoreconf -i

      - run: |
          cd gifsicle-1.93
          ./configure

      - run: |
          cd gifsicle-1.93
          make install
