name: terminal

on:
  push:
    branches: [main]

jobs:
  terminal:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          repository: kohler/gifsicle

      - run: autoreconf -i
      - run: ./configure
      - run: make install
