name: terminal

on:
  push:
    branches: [main]

jobs:
  terminal:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - run: autoscan
      - run: ls
