name: terminal

on:
  push:
    branches: [main]

jobs:
  terminal:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - run: curl -sL http://www.lcdf.org/gifsicle/gifsicle-1.91.tar.gz | tar -zx
      - run: |
          autoscan
          mv ./configure.scan ./configure.ac
          autoreconf -i
          ./configure
          make install
        working-directory: gifsicle-1.91
